# Generated by Django 4.2.17 on 2025-01-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pos',
            new_name='Post',
        ),
    ]
